"""added surname column to user table

Revision ID: 9d04a47a4695
Revises: 
Create Date: 2021-09-12 18:57:26.189473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d04a47a4695'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('surname', sa.String(length=80), nullable=True))
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)
    op.drop_column('user', 'surname')
    # ### end Alembic commands ###
